### PR TITLE
Update driver to use JS resolver

### PR DESCRIPTION
**Pull request by christianlundkvist**
Updates the Universal resolver driver to use the JS DID resolver.

### CODE REVIEW

**Comment by ajunge** [comment]
Looks good. I tested with all DIDs and works fine!

**Comment by ajunge** [comment]
I think you need to upgrade the driver version to 1.1.0 since it adds support for this DIDs:
`did:muport:`
`did:eth:`
`did:ethr:`

along with
`did:uport:`

**Comment by christianlundkvist** [comment]
Good point about the version @ajunge and @oed, I'll update that!

**Comment by christianlundkvist** [comment]
@oed @ajunge  Updated the version, added to README and updated the API path to use `/identifiers/` rather than `/dids/`.

**Comment by oed** [comment]
lgmt!

**Comment by ajunge** [comment]
Looks good to me. Go merge it!

**Pull request merged**
